[package]
name = "big_clock"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = [ "cdylib" ]


[lints.rust]
unused_parens = "allow"


[dependencies.flywheel-sys]
path     = "../../"
features = [ "selfhosted", "chrono" ]
